before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
before_script:
cache:
  - bundler
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
sudo: false
script: bundle exec rspec spec/
