require 'aws-sdk'
require 'json'
require 'erubis'
require 'diffy'
require 'netaddr'
require './lib/cluster/rake_docs'
require './lib/cluster/waiters'
require './lib/cluster/configuration_helpers'
require './lib/cluster/naming_helpers'
require './lib/cluster/client_helpers'
require './lib/cluster/base'
require './lib/cluster/app'
require './lib/cluster/deployment'
require './lib/cluster/instance_syncer'
require './lib/cluster/instance'
require './lib/cluster/instances'
require './lib/cluster/sns'
require './lib/cluster/subscribes_sns_endpoints'
require './lib/cluster/cwlogs'
require './lib/cluster/sqs'
require './lib/cluster/layers'
require './lib/cluster/layer'
require './lib/cluster/auto_scaling_config'
require './lib/cluster/permissions_syncer'
require './lib/cluster/config'
require './lib/cluster/iam_user'
require './lib/cluster/user'
require './lib/cluster/vpc'
require './lib/cluster/rds'
require './lib/cluster/registers_rds_instance'
require './lib/cluster/security_group_finder'
require './lib/cluster/assets'
require './lib/cluster/s3_bucket'
require './lib/cluster/s3_distribution_bucket'
require './lib/cluster/s3_archive_bucket'
require './lib/cluster/s3_cold_archive_bucket'
require './lib/cluster/s3_analytics_buckets'
require './lib/cluster/instance_profile'
require './lib/cluster/service_role'
require './lib/cluster/stack'
require './lib/cluster/console'
require './lib/cluster/seed_file_chooser'
require './lib/cluster/az_picker'
require './lib/cluster/ami_finder'
require './lib/cluster/remote_configs'
require './lib/cluster/remote_config'
require './lib/cluster/config_creator'
require './lib/cluster/config_creation_session'
require './lib/cluster/cluster_switcher_session'
require './lib/cluster/rc_file_switcher'
require './lib/cluster/execute_recipe_on_deployment_layers'
require './lib/cluster/config_checks/cluster_compatibility'
require './lib/cluster/config_checks/deployment'
require './lib/cluster/config_checks/numbered_layer'
require './lib/cluster/config_checks/database'
require './lib/cluster/config_checks/admin'
require './lib/cluster/config_checks/engage'
require './lib/cluster/config_checks/monitoring'
require './lib/cluster/config_checks/cidr_nfs_parity'
require './lib/cluster/config_checks/storage'
require './lib/cluster/config_checks/json_format'
require './lib/cluster/config_checks/bucket_configs'
require './lib/cluster/config_checks/real_users'
require './lib/cluster/config_checks/secrets_ips'
require './lib/cluster/config_checks/prebuilt_oc'
require './lib/cluster/zadara'

module Cluster
  class JSONFormatError < StandardError; end
  class VpcConflictsWithAnother < StandardError; end
  class StackConflictsWithAnother < StandardError; end
  class StackNotInitialized < StandardError; end
  class NoRecipesToRun < StandardError; end
end
