AWSTemplateFormatVersion : '2010-09-09'
Description: DCE Opencast Analytics services & tools

Parameters:

  ESInstanceCount:
    Type: Number

  ESInstanceType:
    Type: String

  OpsworksStackName:
    Type: String

Resources:

  StuffBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-stuff"

  AnalyticsES:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: 6.0
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        InstanceCount: !Ref ESInstanceCount
        InstanceType: !Ref ESInstanceType
        DedicatedMasterType: !Ref ESInstanceType
        DedicatedMasterCount: 3
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: 6
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: "*"
      VPCOptions:
        SubnetIds:
           - Fn::ImportValue:
              !Sub "${OpsworksStackName}-vpc-private-subnet"
        SecurityGroupIds:
           - Fn::ImportValue:
              !Sub "${OpsworksStackName}-vpc-common-sg"

  AnalyticsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                   - "es:*"
                Resource: !GetAtt [AnalyticsES, DomainArn]

Outputs:

  StuffBucket:
    Description: "A bucket for analytics stuff"
    Value: !Ref StuffBucket
